#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libical-soname2
Version  : 2.0.0
Release  : 7
URL      : https://github.com/libical/libical/archive/v2.0.0.tar.gz
Source0  : https://github.com/libical/libical/archive/v2.0.0.tar.gz
Summary  : An implementation of basic iCAL protocols
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: compat-libical-soname2-lib = %{version}-%{release}
Requires: compat-libical-soname2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : doxygen
BuildRequires : icu4c-dev
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(gobject-introspection-1.0)
Patch1: CVE-2016-9584.patch

%description
Arnout Engelen pointed out, that you could create a php libical wrapper:
PHP currently seems to lack proper iCalendar libraries.
Since there already is a LibicalWrap.i for the Python
bindings, it's not very hard to make a libical .so that
can be accessed from PHP. Would be a valuable building
block in the practical adoption of the iCalendar
standard (imho).

%package dev
Summary: dev components for the compat-libical-soname2 package.
Group: Development
Requires: compat-libical-soname2-lib = %{version}-%{release}
Provides: compat-libical-soname2-devel = %{version}-%{release}
Requires: compat-libical-soname2 = %{version}-%{release}

%description dev
dev components for the compat-libical-soname2 package.


%package lib
Summary: lib components for the compat-libical-soname2 package.
Group: Libraries
Requires: compat-libical-soname2-license = %{version}-%{release}

%description lib
lib components for the compat-libical-soname2 package.


%package license
Summary: license components for the compat-libical-soname2 package.
Group: Default

%description license
license components for the compat-libical-soname2 package.


%prep
%setup -q -n libical-2.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562627723
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1562627723
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libical-soname2
cp COPYING %{buildroot}/usr/share/package-licenses/compat-libical-soname2/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/compat-libical-soname2/LICENSE
cp debian/copyright %{buildroot}/usr/share/package-licenses/compat-libical-soname2/debian_copyright
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/libical/ical.h
%exclude /usr/include/libical/icalarray.h
%exclude /usr/include/libical/icalattach.h
%exclude /usr/include/libical/icalcalendar.h
%exclude /usr/include/libical/icalclassify.h
%exclude /usr/include/libical/icalcluster.h
%exclude /usr/include/libical/icalcomponent.h
%exclude /usr/include/libical/icalderivedparameter.h
%exclude /usr/include/libical/icalderivedproperty.h
%exclude /usr/include/libical/icalderivedvalue.h
%exclude /usr/include/libical/icaldirset.h
%exclude /usr/include/libical/icaldirsetimpl.h
%exclude /usr/include/libical/icalduration.h
%exclude /usr/include/libical/icalenums.h
%exclude /usr/include/libical/icalerror.h
%exclude /usr/include/libical/icalfileset.h
%exclude /usr/include/libical/icalfilesetimpl.h
%exclude /usr/include/libical/icalgauge.h
%exclude /usr/include/libical/icalgaugeimpl.h
%exclude /usr/include/libical/icallangbind.h
%exclude /usr/include/libical/icalmemory.h
%exclude /usr/include/libical/icalmessage.h
%exclude /usr/include/libical/icalmime.h
%exclude /usr/include/libical/icalparameter.h
%exclude /usr/include/libical/icalparameter_cxx.h
%exclude /usr/include/libical/icalparser.h
%exclude /usr/include/libical/icalperiod.h
%exclude /usr/include/libical/icalproperty.h
%exclude /usr/include/libical/icalproperty_cxx.h
%exclude /usr/include/libical/icalrecur.h
%exclude /usr/include/libical/icalrestriction.h
%exclude /usr/include/libical/icalset.h
%exclude /usr/include/libical/icalspanlist.h
%exclude /usr/include/libical/icalspanlist_cxx.h
%exclude /usr/include/libical/icalss.h
%exclude /usr/include/libical/icalssyacc.h
%exclude /usr/include/libical/icaltime.h
%exclude /usr/include/libical/icaltimezone.h
%exclude /usr/include/libical/icaltypes.h
%exclude /usr/include/libical/icaltz-util.h
%exclude /usr/include/libical/icalvalue.h
%exclude /usr/include/libical/icalvalue_cxx.h
%exclude /usr/include/libical/icalvcal.h
%exclude /usr/include/libical/icptrholder_cxx.h
%exclude /usr/include/libical/libical_ical_export.h
%exclude /usr/include/libical/libical_icalss_export.h
%exclude /usr/include/libical/libical_vcal_export.h
%exclude /usr/include/libical/pvl.h
%exclude /usr/include/libical/sspm.h
%exclude /usr/include/libical/vcaltmp.h
%exclude /usr/include/libical/vcc.h
%exclude /usr/include/libical/vcomponent_cxx.h
%exclude /usr/include/libical/vobject.h
%exclude /usr/lib64/cmake/LibIcal/LibIcalConfig.cmake
%exclude /usr/lib64/cmake/LibIcal/LibIcalConfigVersion.cmake
%exclude /usr/lib64/cmake/LibIcal/LibIcalTargets-relwithdebinfo.cmake
%exclude /usr/lib64/cmake/LibIcal/LibIcalTargets.cmake
%exclude /usr/lib64/libical.so
%exclude /usr/lib64/libical_cxx.so
%exclude /usr/lib64/libicalss.so
%exclude /usr/lib64/libicalss_cxx.so
%exclude /usr/lib64/libicalvcal.so
%exclude /usr/lib64/pkgconfig/libical.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libical.so.2
/usr/lib64/libical.so.2.0.0
/usr/lib64/libical_cxx.so.2
/usr/lib64/libical_cxx.so.2.0.0
/usr/lib64/libicalss.so.2
/usr/lib64/libicalss.so.2.0.0
/usr/lib64/libicalss_cxx.so.2
/usr/lib64/libicalss_cxx.so.2.0.0
/usr/lib64/libicalvcal.so.2
/usr/lib64/libicalvcal.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libical-soname2/COPYING
/usr/share/package-licenses/compat-libical-soname2/LICENSE
/usr/share/package-licenses/compat-libical-soname2/debian_copyright
